version: '3.9'
services:
  bot:
    image: andrewlevin/ytb2audiobot
    environment:
      - BOT_TOKEN=7287463773:AAFiIKRGJLt1TVb_dESjo96gmmP4jtpo6XE
      - SALT=013bf983d5a4a2634defdc414c53b02d2737fdce8cd07624605fe58753055598
    restart: on-failure:3
